org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
#org.gradle.configuration-cache=true

group              = com.filloax.filloaxlib
archives_base_name = filloaxlib
modid              = filloaxlib
modName            = FilloaxLib
modDescription     = Common utilities for Filloax's mods
modIcon            = assets/filloaxlib/icon.png
author             = Filloax
license            = MIT
displayUrl         =

javaVersion = 25
