modLoader="kotlinforforge"
loaderVersion="${kotlinforge_version_range}"

license="${license}"
issueTrackerURL="https://github.com/filloax/filloax-lib"

[[mods]]
    modId="${mod_id}"
    version="${version_prefix}-neoforge"
    displayName="${mod_name}"

    displayURL="${display_url}"
    logoFile="${mod_icon}"
    authors='''${author}
    Contributions
    kotlin-events by svby
    '''
    description='''${description}'''

[[dependencies]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"

[[dependencies]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"

[mc-publish]
    modrinth="JAKPaut3"