on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'pull_request'"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      java_version: ${{ steps.java_version.outputs.javaVersion }}
      mc_version: ${{ steps.mc_version.outputs.value }}
      mc_version_range: ${{ steps.mc_version_range.outputs.value }}

    steps:
    - uses: actions/checkout@v4

    - name: "Read Java version"
      uses: BrycensRanch/read-properties-action@v1.0.4
      id: java_version
      with:
        file: gradle.properties
        property: javaVersion

    - name: "Read MC version"
      uses: SebRollen/toml-action@v1.2.0
      id: mc_version
      with:
        file: 'gradle/libs.versions.toml'
        field: 'versions.minecraft'

    - name: "Read MC version range"
      uses: SebRollen/toml-action@v1.2.0
      id: mc_version_range
      with:
        file: 'gradle/libs.versions.toml'
        field: 'versions.minecraft-range'

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ steps.java_version.outputs.javaVersion }}
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}

    - name: Make Gradle Wrapper Executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

    - name: Get version from gradle
      id: get_version
      run: |
        VERSION=$(grep -m1 'modversion' gradle/libs.versions.toml | sed 's/.*= *"\(.*\)"/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Build with Gradle
      run: ./gradlew build

    - name: Extract latest changelog
      run: |
        awk '/^## /{if(found)exit; found=1} found{print}' CHANGELOG.md > latest_changelog.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          base/build/libs/*.jar
          fabric/build/libs/*.jar
          neoforge/build/libs/*.jar
          latest_changelog.txt

  release-github:
    name: Release (GitHub + Jitpack)
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Publish (GitHub)
      id: publish_github
      uses: softprops/action-gh-release@v2
      with:
        name: FilloaxLib ${{ needs.build.outputs.version }} - ${{ needs.build.outputs.mc_version }}
        body_path: latest_changelog.txt
        token: ${{ secrets.GITHUB_TOKEN }}
        make_latest: true
        tag_name: "${{ needs.build.outputs.version }}-${{ needs.build.outputs.mc_version }}"
        target_commitish: ${{ github.sha }}
        files: |
          base/build/libs/*.jar
          fabric/build/libs/*.jar
          neoforge/build/libs/*.jar

    - name: Trigger Jitpack build
      if: steps.publish_github.outcome == 'success'
      run: |
        sleep 10s && curl --max-time 0 -L \
          https://jitpack.io/com/github/filloax/filloaxlib/filloaxlib-common/${{ needs.build.outputs.version }}-${{ needs.build.outputs.mc_version }}/filloaxlib-common-${{ needs.build.outputs.version }}-${{ needs.build.outputs.mc_version }}.pom

  release-platform:
    name: Publish (${{ matrix.name }})
    needs: build
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'chore: release-github-only') }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: neoforge
            name: Neoforge
            dependencies: |
              kotlin-for-forge(required)
          - platform: fabric
            name: Fabric
            dependencies: |
              fabric-language-kotlin(required)
              fabric-api(required)

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Publish
      uses: Kir-Antipov/mc-publish@v3.3
      id: mc_publish
      with:
        modrinth-token: ${{ secrets.TOKEN_MODRINTH }}
        modrinth-id: JAKPaut3
        name: FilloaxLib ${{ needs.build.outputs.version }} - ${{ needs.build.outputs.mc_version }} ${{ matrix.name }}
        version: "${{ needs.build.outputs.version }}-${{ needs.build.outputs.mc_version }}-${{ matrix.platform }}"
        version-type: beta
        files: |
          ${{ matrix.platform }}/build/libs/!(*-@(dev|sources|javadoc)).jar
          ${{ matrix.platform }}/build/libs/*-@(dev|sources|javadocs).jar
        game-versions: ${{ needs.build.outputs.mc_version_range }}
        dependencies: ${{ matrix.dependencies }}
        java: ${{ needs.build.outputs.java_version }}
        loaders: ${{ matrix.platform }}
        changelog-file: latest_changelog.txt

    - run: echo "Published ${{ matrix.name }}!"